github.com:
    users:
        agenciarodrigues:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: agenciarodrigues
